// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI
//
// ocudu-side Metal engine that drives the SynchroPlus LDPC decoder shaders
// (decode/ldpc_gpu_decoder.metal, copied verbatim). It mirrors the GPUEngineImpl
// contract of the SynchroPlus ldpc_gpu_decoder.mm exactly - buffer indices,
// dispatch sizes and the DecodeCtrl/VNStats layouts are the shader ABI - but it
// initializes the shader library either from an offline-compiled metallib (when
// the Xcode Metal toolchain built one) or from the .metal source embedded at
// configure time, compiled at runtime with newLibraryWithSource.

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <cstring>
#include <unordered_map>

#include "ocudu_metal_decoder_engine.h"
#include "ldpc_gpu_decoder_metal_source.h"         // generated by CMake (embedded LLS .metal source)
#include "ocudu_nms_decoder_metal_source.h"        // generated by CMake (embedded NMS .metal source)
#include "ocudu_nms_layered_decoder_metal_source.h" // generated by CMake (embedded layered NMS source)

namespace ocudu {
namespace metal {

// Must match the DecodeCtrl struct in ldpc_gpu_decoder.metal (shader ABI).
struct decode_ctrl_t {
  uint32_t error_count;     // unsatisfied check equations (current iteration)
  uint32_t early_terminate; // set by the shaders when the syndrome converges
  uint32_t actual_iters;    // iterations actually executed
};

// Must match the LayerDesc struct in ocudu_nms_layered_decoder.metal (shader ABI).
struct layer_desc_t {
  uint32_t layer;
  uint32_t nof_cols;
  uint32_t cols[20];
};

// Must match the VNStats struct in ldpc_gpu_decoder.metal (debug buffer layout).
struct vn_stats_t {
  uint32_t err_eq_cnt;
  uint32_t suspect_cnt;
  float    evid_sum;
  float    vn_total_cn;
  float    last_delta;
  float    current_llr;
};

struct engine_impl_t {
  id<MTLDevice>              device = nil;
  id<MTLCommandQueue>        queue  = nil;
  // LLS pipelines (SynchroPlus kernels).
  id<MTLComputePipelineState> p_init = nil;
  id<MTLComputePipelineState> p_syndrome = nil;
  id<MTLComputePipelineState> p_scan = nil;
  id<MTLComputePipelineState> p_update = nil;
  // NMS pipelines (ocudu kernels).
  id<MTLComputePipelineState> p_nms_init = nil;
  id<MTLComputePipelineState> p_nms_syndrome = nil;
  id<MTLComputePipelineState> p_nms_cn = nil;
  id<MTLComputePipelineState> p_nms_vn = nil;

  // Zero-copy wrappers, cached by host pointer (the host buffers outlive the engine).
  std::unordered_map<const void*, id<MTLBuffer>> buffer_cache;

  id<MTLBuffer> buf_h        = nil; // zero-copy
  id<MTLBuffer> buf_ht       = nil; // zero-copy
  id<MTLBuffer> buf_vn_total = nil; // zero-copy (CPU-written, GPU read-only; LLS only)
  id<MTLBuffer> buf_ctrl     = nil; // shared (GPU writes, CPU reads)
  id<MTLBuffer> buf_s_hard   = nil; // private
  id<MTLBuffer> buf_h_pred   = nil; // shared (CPU recomputes the final syndrome)
  id<MTLBuffer> buf_err_eq   = nil; // private (LLS only)
  id<MTLBuffer> buf_suspect  = nil; // private (LLS only)
  id<MTLBuffer> buf_evidence = nil; // private (LLS only)
  id<MTLBuffer> buf_debug    = nil; // shared (VNStats; LLS only)
  // NMS pipelines (layered schedule).
  id<MTLComputePipelineState> p_nmsl_init = nil;
  id<MTLComputePipelineState> p_nmsl_cn = nil;
  id<MTLComputePipelineState> p_nmsl_vn = nil;

  // NMS-only state.
  id<MTLBuffer> buf_llr_chan   = nil; // private (channel LLR copy)
  id<MTLBuffer> buf_min1       = nil; // private (per check row)
  id<MTLBuffer> buf_min2       = nil; // private (per check row)
  id<MTLBuffer> buf_idx_min1   = nil; // private (per check row)
  id<MTLBuffer> buf_h_pred_bits = nil; // shared (one word per row, CPU recomputes the final syndrome)
  // Layered-NMS-only state.
  id<MTLBuffer> buf_row_start  = nil; // zero-copy CSR offsets (M_aligned + 1)
  id<MTLBuffer> buf_edge_vn    = nil; // zero-copy CSR edge VN indices
  id<MTLBuffer> buf_c2v        = nil; // private (per-edge messages, no_edges fp16)
  id<MTLBuffer> buf_vn_delta   = nil; // private (per-VN layer deltas, N_aligned fp16)
  decoder_engine::layered_info layered_info{};

  decoder_engine::algo mode = decoder_engine::algo::lls;

  uint32_t n_aligned   = 0;
  uint32_t m_aligned   = 0;
  uint32_t n_h_chunks  = 0;
  uint32_t h_pred_len  = 0;
  uint32_t n_info      = 0;
  uint32_t z           = 0;
  float    factor      = 0.0f;
  float    sat         = 0.0f;
};

namespace {

id<MTLBuffer> zero_copy_buffer(engine_impl_t* engine, const void* ptr, size_t length)
{
  auto it = engine->buffer_cache.find(ptr);
  if (it != engine->buffer_cache.end()) {
    return it->second;
  }
  size_t aligned = (length + 4095) & ~4095;
  id<MTLBuffer> buf =
      [engine->device newBufferWithBytesNoCopy:(void*)ptr
                                        length:aligned
                                       options:MTLResourceStorageModeShared
                                   deallocator:nil];
  if (buf == nil) {
    buf = [engine->device newBufferWithBytes:ptr length:length options:MTLResourceStorageModeShared];
  }
  engine->buffer_cache[ptr] = buf;
  return buf;
}

} // namespace

decoder_engine::~decoder_engine()
{
  engine_impl_t* engine = static_cast<engine_impl_t*>(impl);
  if (engine != nullptr) {
    engine->buffer_cache.clear();
    delete engine;
    impl = nullptr;
  }
}

bool decoder_engine::init(uint32_t n_logical, uint32_t m_logical, float factor, const uint32_t* h,
                          const uint32_t* ht, uint32_t* col_weights_out, algo mode, float sat,
                          const layered_info* layered)
{
  engine_impl_t* engine = new engine_impl_t();
  impl                  = engine;

  engine->n_info = n_logical - m_logical;
  engine->factor = factor;
  engine->mode   = mode;
  engine->sat    = sat;
  engine->z      = 1;
  if (layered != nullptr) {
    engine->layered_info = *layered;
    engine->z            = layered->z;
  }

  engine->n_aligned  = ((n_logical + 31) / 32) * 32;
  engine->m_aligned  = ((m_logical + 31) / 32) * 32;
  engine->n_h_chunks = engine->n_aligned / 32;
  engine->h_pred_len = engine->m_aligned / 32;

  engine->device = MTLCreateSystemDefaultDevice();
  if (engine->device == nil) {
    NSLog(@"ocudu Metal LDPC: no Metal device available");
    return false;
  }
  engine->queue = [engine->device newCommandQueue];

  // Prefer the offline-compiled metallib; fall back to runtime compilation of the
  // embedded source (works on Command-Line-Tools-only machines without Xcode).
  // The offline metallib only bundles the LLS shader (the NMS shader compiles at runtime).
  NSError*       error   = nil;
  id<MTLLibrary> library = nil;
  if (mode == algo::lls) {
    NSString* metallib_path = [NSString stringWithUTF8String:OCUDU_METAL_DECODER_METALLIB_PATH];
    if ([[NSFileManager defaultManager] fileExistsAtPath:metallib_path]) {
      library = [engine->device newLibraryWithURL:[NSURL fileURLWithPath:metallib_path] error:&error];
      if (library == nil) {
        NSLog(@"ocudu Metal LDPC: metallib load failed (%@); falling back to runtime compilation",
              error);
        error = nil;
      }
    }
  }
  if (library == nil) {
    const char* src_bytes = (mode == algo::lls)          ? (const char*)ldpc_gpu_decoder_metal_source
                            : (mode == algo::nms_layered) ? (const char*)ocudu_nms_layered_decoder_metal_source
                                                          : (const char*)ocudu_nms_decoder_metal_source;
    NSString* src = [NSString stringWithUTF8String:src_bytes];
    library        = [engine->device newLibraryWithSource:src options:nil error:&error];
    if (library == nil) {
      NSLog(@"ocudu Metal LDPC: shader runtime compilation failed: %@", error);
      return false;
    }
  }

  auto make_pipeline = [&](id<MTLComputePipelineState> __strong* out, const char* name) -> bool {
    id<MTLFunction> fn = [library newFunctionWithName:[NSString stringWithUTF8String:name]];
    if (fn == nil) {
      NSLog(@"ocudu Metal LDPC: kernel '%s' not found in the shader library", name);
      return false;
    }
    *out = [engine->device newComputePipelineStateWithFunction:fn error:&error];
    if (*out == nil) {
      NSLog(@"ocudu Metal LDPC: pipeline '%s' failed: %@", name, error);
      return false;
    }
    return true;
  };
  if (mode == algo::lls) {
    if (!make_pipeline(&engine->p_init, "init_hard_decisions") ||
        !make_pipeline(&engine->p_syndrome, "compute_syndrome") ||
        !make_pipeline(&engine->p_scan, "cn_centric_scan") ||
        !make_pipeline(&engine->p_update, "update_llr_hpred")) {
      return false;
    }
  } else if (mode == algo::nms_layered) {
    if (!make_pipeline(&engine->p_nmsl_init, "nmsl_init") ||
        !make_pipeline(&engine->p_nmsl_cn, "nmsl_cn_update") ||
        !make_pipeline(&engine->p_nmsl_vn, "nmsl_vn_update") ||
        !make_pipeline(&engine->p_nms_cn, "nmsl_final_syndrome")) {
      return false;
    }
  } else {
    if (!make_pipeline(&engine->p_nms_init, "nms_init_hard") ||
        !make_pipeline(&engine->p_nms_cn, "nms_cn_update") ||
        !make_pipeline(&engine->p_nms_vn, "nms_vn_update")) {
      return false;
    }
  }

  engine->buf_ctrl = [engine->device newBufferWithLength:sizeof(decode_ctrl_t)
                                                 options:MTLResourceStorageModeShared];

  // Shared (not private): the CPU recomputes the final syndrome after the kernels
  // complete (the shaders clear ctrl->error_count at the end of every iteration,
  // so it cannot serve as the final syndrome).
  engine->buf_h_pred   = [engine->device newBufferWithLength:engine->h_pred_len * sizeof(uint32_t)
                                                     options:MTLResourceStorageModeShared];

  if (mode == algo::lls) {
    // Intermediate state fully consumed by the GPU: private storage.
    engine->buf_s_hard = [engine->device newBufferWithLength:engine->n_h_chunks * sizeof(uint32_t)
                                                     options:MTLResourceStorageModePrivate];
    engine->buf_debug = [engine->device newBufferWithLength:engine->n_aligned * sizeof(vn_stats_t)
                                                    options:MTLResourceStorageModeShared];
    engine->buf_err_eq   = [engine->device newBufferWithLength:engine->n_aligned * sizeof(uint32_t)
                                                       options:MTLResourceStorageModePrivate];
    engine->buf_suspect  = [engine->device newBufferWithLength:engine->n_aligned * sizeof(uint32_t)
                                                       options:MTLResourceStorageModePrivate];
    engine->buf_evidence = [engine->device newBufferWithLength:engine->n_aligned * sizeof(float)
                                                       options:MTLResourceStorageModePrivate];
  } else {
    engine->buf_min1     = [engine->device newBufferWithLength:engine->m_aligned * sizeof(float)
                                                       options:MTLResourceStorageModePrivate];
    engine->buf_min2     = [engine->device newBufferWithLength:engine->m_aligned * sizeof(float)
                                                       options:MTLResourceStorageModePrivate];
    engine->buf_idx_min1 = [engine->device newBufferWithLength:engine->m_aligned * sizeof(uint32_t)
                                                       options:MTLResourceStorageModePrivate];
    engine->buf_h_pred_bits = [engine->device newBufferWithLength:engine->m_aligned * sizeof(uint32_t)
                                                          options:MTLResourceStorageModeShared];
    if (mode == algo::nms) {
      engine->buf_llr_chan = [engine->device newBufferWithLength:engine->n_aligned * sizeof(uint16_t)
                                                         options:MTLResourceStorageModePrivate];
    } else {
      // Layered: CSR edge layout (zero-copy) + per-edge messages + per-VN deltas.
      engine->buf_row_start = zero_copy_buffer(
          engine, engine->layered_info.row_start,
          static_cast<size_t>(engine->m_aligned + 1) * sizeof(uint32_t));
      engine->buf_edge_vn = zero_copy_buffer(
          engine, engine->layered_info.edge_vn,
          static_cast<size_t>(engine->layered_info.no_edges) * sizeof(uint32_t));
      engine->buf_c2v = [engine->device newBufferWithLength:engine->layered_info.no_edges * sizeof(uint16_t)
                                                    options:MTLResourceStorageModePrivate];
      engine->buf_vn_delta = [engine->device newBufferWithLength:engine->n_aligned * sizeof(uint16_t)
                                                         options:MTLResourceStorageModePrivate];
    }
  }

  // Zero-copy wrap the host-side matrices (4KB-aligned, owned by the caller).
  engine->buf_h = zero_copy_buffer(engine, h, static_cast<size_t>(engine->m_aligned) *
                                                 engine->n_h_chunks * sizeof(uint32_t));
  engine->buf_ht = zero_copy_buffer(engine, ht, static_cast<size_t>(engine->n_aligned) *
                                                    engine->h_pred_len * sizeof(uint32_t));

  if (mode == algo::lls) {
    engine->buf_vn_total =
        zero_copy_buffer(engine, col_weights_out, static_cast<size_t>(engine->n_aligned) * sizeof(uint32_t));

    // Compute the column weights on the CPU (GPU reads them read-only).
    std::memset(col_weights_out, 0, static_cast<size_t>(engine->n_aligned) * sizeof(uint32_t));
    for (uint32_t r = 0; r != engine->m_aligned; ++r) {
      const uint32_t* row_base = h + r * engine->n_h_chunks;
      for (uint32_t c = 0; c != engine->n_h_chunks; ++c) {
        uint32_t mask = row_base[c];
        uint32_t col_base = c * 32;
        while (mask != 0) {
          uint32_t bit = static_cast<uint32_t>(__builtin_ctz(mask));
          if (col_base + bit < engine->n_aligned) {
            col_weights_out[col_base + bit]++;
          }
          mask &= (mask - 1);
        }
      }
    }
  }

  return true;
}

int decoder_engine::decode(const void* in_fp16, uint8_t* out_bits, int max_iter, uint32_t* error_count_out)
{
  engine_impl_t* engine = static_cast<engine_impl_t*>(impl);
  const bool     is_nms = engine != nullptr && engine->mode == algo::nms;
  const bool     is_layered = engine != nullptr && engine->mode == algo::nms_layered;
  if (engine == nullptr ||
      (is_layered ? engine->p_nmsl_init == nil : (is_nms ? engine->p_nms_init == nil : engine->p_init == nil))) {
    return -1;
  }
  id<MTLBuffer> mtl_llr =
      zero_copy_buffer(engine, in_fp16, static_cast<size_t>(engine->n_aligned) * sizeof(uint16_t));
  id<MTLCommandBuffer>        cmd_buf = [engine->queue commandBuffer];
  id<MTLComputeCommandEncoder> enc    = [cmd_buf computeCommandEncoder];

  // Stage A: hard-decision init and control-block reset.
  if (is_layered) {
    [enc setComputePipelineState:engine->p_nmsl_init];
    [enc setBuffer:engine->buf_c2v offset:0 atIndex:0];
    [enc setBuffer:engine->buf_ctrl offset:0 atIndex:1];
    [enc dispatchThreadgroups:MTLSizeMake((engine->layered_info.no_edges + 31) / 32, 1, 1)
        threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
  } else if (is_nms) {
    [enc setComputePipelineState:engine->p_nms_init];
    [enc setBuffer:mtl_llr offset:0 atIndex:0];
    [enc setBuffer:engine->buf_llr_chan offset:0 atIndex:1];
    [enc setBuffer:engine->buf_ctrl offset:0 atIndex:2];
    [enc dispatchThreads:MTLSizeMake(engine->n_aligned, 1, 1) threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
  } else {
    [enc setComputePipelineState:engine->p_init];
    [enc setBuffer:mtl_llr offset:0 atIndex:0];
    [enc setBuffer:engine->buf_s_hard offset:0 atIndex:1];
    [enc setBuffer:engine->buf_ctrl offset:0 atIndex:2];
    [enc setBuffer:engine->buf_err_eq offset:0 atIndex:3];
    [enc setBuffer:engine->buf_suspect offset:0 atIndex:4];
    [enc setBuffer:engine->buf_evidence offset:0 atIndex:5];
    [enc dispatchThreads:MTLSizeMake(engine->n_aligned, 1, 1) threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
  }

  // Stage B: initial full syndrome computation (once; LLS only - the NMS CN
  // kernel computes the row parities in its own pass every round).
  if (!is_nms && !is_layered) {
    [enc setComputePipelineState:engine->p_syndrome];
    [enc setBuffer:engine->buf_h offset:0 atIndex:0];
    [enc setBuffer:engine->buf_s_hard offset:0 atIndex:1];
    [enc setBuffer:engine->buf_h_pred offset:0 atIndex:2];
    [enc setBuffer:engine->buf_ctrl offset:0 atIndex:3];
    [enc setBytes:&engine->n_h_chunks length:sizeof(uint32_t) atIndex:4];
    [enc dispatchThreadgroups:MTLSizeMake(engine->h_pred_len, 1, 1)
        threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
  }

  // Stage C: unrolled iteration loop, fully consumed by the GPU.
  for (int it = 0; it < max_iter; ++it) {
    if (is_layered) {
      for (uint32_t l = 0; l != engine->layered_info.n_layers; ++l) {
        const uint32_t layer_start = l * engine->z;
        [enc setComputePipelineState:engine->p_nmsl_cn];
        [enc setBuffer:engine->buf_row_start offset:0 atIndex:0];
        [enc setBuffer:engine->buf_edge_vn offset:0 atIndex:1];
        [enc setBuffer:engine->buf_c2v offset:0 atIndex:2];
        [enc setBuffer:engine->buf_vn_delta offset:0 atIndex:3];
        [enc setBuffer:mtl_llr offset:0 atIndex:4];
        [enc setBuffer:engine->buf_h_pred_bits offset:0 atIndex:5];
        [enc setBytes:&layer_start length:sizeof(uint32_t) atIndex:6];
        [enc setBytes:&engine->factor length:sizeof(float) atIndex:7];
        [enc dispatchThreadgroups:MTLSizeMake(engine->z, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];

        const layer_desc_t* desc =
            reinterpret_cast<const layer_desc_t*>(engine->layered_info.layer_descs + l * 22);
        [enc setComputePipelineState:engine->p_nmsl_vn];
        [enc setBuffer:mtl_llr offset:0 atIndex:0];
        [enc setBuffer:engine->buf_vn_delta offset:0 atIndex:1];
        [enc setBytes:desc length:sizeof(layer_desc_t) atIndex:2];
        [enc setBytes:&engine->z length:sizeof(uint32_t) atIndex:3];
        [enc setBytes:&engine->sat length:sizeof(float) atIndex:4];
        [enc dispatchThreadgroups:MTLSizeMake(desc->nof_cols, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(engine->z, 1, 1)];
      }
      // Final syndrome refresh from the final soft bits (per-round, cheap).
      [enc setComputePipelineState:engine->p_nms_cn];
      [enc setBuffer:engine->buf_h offset:0 atIndex:0];
      [enc setBuffer:mtl_llr offset:0 atIndex:1];
      [enc setBuffer:engine->buf_h_pred_bits offset:0 atIndex:2];
      [enc setBytes:&engine->n_h_chunks length:sizeof(uint32_t) atIndex:3];
      [enc dispatchThreadgroups:MTLSizeMake(engine->m_aligned, 1, 1)
          threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
    } else if (is_nms) {
      [enc setComputePipelineState:engine->p_nms_cn];
      [enc setBuffer:engine->buf_h offset:0 atIndex:0];
      [enc setBuffer:mtl_llr offset:0 atIndex:1];
      [enc setBuffer:engine->buf_h_pred_bits offset:0 atIndex:2];
      [enc setBuffer:engine->buf_min1 offset:0 atIndex:3];
      [enc setBuffer:engine->buf_min2 offset:0 atIndex:4];
      [enc setBuffer:engine->buf_idx_min1 offset:0 atIndex:5];
      [enc setBuffer:engine->buf_ctrl offset:0 atIndex:6];
      [enc setBytes:&engine->n_h_chunks length:sizeof(uint32_t) atIndex:7];
      [enc dispatchThreadgroups:MTLSizeMake(engine->m_aligned, 1, 1)
          threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];

      [enc setComputePipelineState:engine->p_nms_vn];
      [enc setBuffer:mtl_llr offset:0 atIndex:0];
      [enc setBuffer:engine->buf_llr_chan offset:0 atIndex:1];
      [enc setBuffer:engine->buf_min1 offset:0 atIndex:2];
      [enc setBuffer:engine->buf_min2 offset:0 atIndex:3];
      [enc setBuffer:engine->buf_idx_min1 offset:0 atIndex:4];
      [enc setBuffer:engine->buf_h_pred_bits offset:0 atIndex:5];
      [enc setBuffer:engine->buf_ht offset:0 atIndex:6];
      [enc setBytes:&engine->h_pred_len length:sizeof(uint32_t) atIndex:7];
      [enc setBytes:&engine->factor length:sizeof(float) atIndex:8];
      [enc setBuffer:engine->buf_ctrl offset:0 atIndex:9];
      [enc setBytes:&engine->sat length:sizeof(float) atIndex:10];
      [enc dispatchThreads:MTLSizeMake(engine->n_aligned, 1, 1)
          threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
    } else {
      [enc setComputePipelineState:engine->p_scan];
      [enc setBuffer:engine->buf_h offset:0 atIndex:0];
      [enc setBuffer:mtl_llr offset:0 atIndex:1];
      [enc setBuffer:engine->buf_h_pred offset:0 atIndex:2];
      [enc setBuffer:engine->buf_err_eq offset:0 atIndex:3];
      [enc setBuffer:engine->buf_suspect offset:0 atIndex:4];
      [enc setBuffer:engine->buf_evidence offset:0 atIndex:5];
      [enc setBytes:&engine->n_h_chunks length:sizeof(uint32_t) atIndex:6];
      [enc setBuffer:engine->buf_ctrl offset:0 atIndex:7];
      [enc dispatchThreadgroups:MTLSizeMake(engine->m_aligned, 1, 1)
          threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];

      [enc setComputePipelineState:engine->p_update];
      [enc setBuffer:mtl_llr offset:0 atIndex:0];
      [enc setBuffer:engine->buf_err_eq offset:0 atIndex:1];
      [enc setBuffer:engine->buf_suspect offset:0 atIndex:2];
      [enc setBuffer:engine->buf_evidence offset:0 atIndex:3];
      [enc setBuffer:engine->buf_vn_total offset:0 atIndex:4];
      [enc setBuffer:engine->buf_h_pred offset:0 atIndex:5];
      [enc setBuffer:engine->buf_ht offset:0 atIndex:6];
      [enc setBytes:&engine->h_pred_len length:sizeof(uint32_t) atIndex:7];
      [enc setBytes:&engine->factor length:sizeof(float) atIndex:8];
      [enc setBuffer:engine->buf_ctrl offset:0 atIndex:9];
      [enc setBuffer:engine->buf_debug offset:0 atIndex:10];
      [enc dispatchThreads:MTLSizeMake(engine->n_aligned, 1, 1)
          threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
    }
  }

  [enc endEncoding];
  [cmd_buf commit];
  [cmd_buf waitUntilCompleted];
  if (cmd_buf.status != MTLCommandBufferStatusCompleted) {
    NSLog(@"ocudu Metal LDPC: command buffer failed with status %lu",
          static_cast<unsigned long>(cmd_buf.status));
    return -1;
  }

  // Extract the results: hard decisions from the final fp16 LLR sign bits.
  const decode_ctrl_t* ctrl = static_cast<const decode_ctrl_t*>(engine->buf_ctrl.contents);
  const uint16_t*      final_llr = static_cast<const uint16_t*>(mtl_llr.contents);
  if (out_bits != nullptr) {
    for (uint32_t i = 0; i != engine->n_info; ++i) {
      out_bits[i] = static_cast<uint8_t>((final_llr[i] >> 15) & 1U);
    }
  }
  if (error_count_out != nullptr) {
    // Recompute the final syndrome on the CPU: the shaders clear ctrl->error_count
    // at the end of every full iteration, so it does not reflect the final state.
    uint32_t errors = 0;
    if (is_nms || is_layered) {
      const uint32_t* h_pred_bits = static_cast<const uint32_t*>(engine->buf_h_pred_bits.contents);
      for (uint32_t w = 0; w != engine->m_aligned; ++w) {
        errors += h_pred_bits[w] & 1u;
      }
    } else {
      const uint32_t* h_pred = static_cast<const uint32_t*>(engine->buf_h_pred.contents);
      for (uint32_t w = 0; w != engine->h_pred_len; ++w) {
        errors += static_cast<uint32_t>(__builtin_popcount(h_pred[w]));
      }
    }
    *error_count_out = errors;
  }
  return is_layered ? max_iter : static_cast<int>(ctrl->actual_iters);
}

uint32_t decoder_engine::get_n_info() const
{
  const engine_impl_t* engine = static_cast<const engine_impl_t*>(impl);
  return engine != nullptr ? engine->n_info : 0;
}

} // namespace metal
} // namespace ocudu
