// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI
//
// ocudu-side Metal engine for the layered normalized min-sum LDPC decoder
// (ocudu_nms_layered_decoder.metal). One command buffer per decode carries the
// whole Gauss-Seidel chain: per-layer CN/VN kernel pairs, a per-round final
// syndrome refresh, and the early-termination gate. The shader is compiled at
// runtime from the source embedded at configure time (no Xcode needed).

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <cstring>
#include <unordered_map>

#include "ocudu_metal_decoder_engine.h"
#include "ocudu_nms_layered_decoder_metal_source.h" // generated by CMake (embedded .metal source)

namespace ocudu {
namespace metal {

// Must match the DecodeCtrl struct in ocudu_nms_layered_decoder.metal (shader ABI).
struct decode_ctrl_t {
  uint32_t error_count;     // unsatisfied check equations (current round)
  uint32_t early_terminate; // set by the ET gate when the syndrome converges
  uint32_t actual_iters;    // rounds actually executed
};

struct engine_impl_t {
  id<MTLDevice>              device = nil;
  id<MTLCommandQueue>        queue  = nil;
  id<MTLComputePipelineState> p_nmsl_init = nil;
  id<MTLComputePipelineState> p_nmsl_convert = nil;
  id<MTLComputePipelineState> p_nmsl_cn = nil;
  id<MTLComputePipelineState> p_nmsl_final_syndrome = nil;
  id<MTLComputePipelineState> p_nmsl_et_gate = nil;

  // Zero-copy wrappers, cached by host pointer (the host buffers outlive the engine).
  std::unordered_map<const void*, id<MTLBuffer>> buffer_cache;

  id<MTLBuffer> buf_h        = nil; // zero-copy (final syndrome refresh)
  id<MTLBuffer> buf_ctrl     = nil; // shared (GPU writes, CPU reads)
  id<MTLBuffer> buf_h_pred_bits = nil; // shared (one word per row; CPU recomputes the final syndrome)
  id<MTLBuffer> buf_row_start  = nil; // zero-copy CSR offsets (M_aligned + 1)
  id<MTLBuffer> buf_edge_vn    = nil; // zero-copy CSR edge VN indices
  id<MTLBuffer> buf_c2v        = nil; // private (per-edge messages, no_edges fp16)
  id<MTLBuffer> buf_llr_fp16   = nil; // shared (fp16 working LLRs; the conversion kernel writes, the hot loop mutates, the CPU reads back)

  decoder_engine::layered_info layered_info{};

  uint32_t n_aligned  = 0;
  uint32_t m_aligned  = 0;
  uint32_t n_h_chunks = 0;
  uint32_t n_info     = 0;
  uint32_t z          = 0;
  float    factor     = 0.0f;
  float    beta       = 0.0f;
  bool     et_enabled = true;
  // GPU-side duration of the last decode (0 when unavailable), for the
  // latency-benchmark breakdown: wall - gpu = CPU-side fixed overhead.
  double   last_gpu_us = 0.0;
};

namespace {

id<MTLBuffer> zero_copy_buffer(engine_impl_t* engine, const void* ptr, size_t length)
{
  auto it = engine->buffer_cache.find(ptr);
  if (it != engine->buffer_cache.end()) {
    return it->second;
  }
  size_t aligned = (length + 4095) & ~4095;
  id<MTLBuffer> buf =
      [engine->device newBufferWithBytesNoCopy:(void*)ptr
                                        length:aligned
                                       options:MTLResourceStorageModeShared
                                   deallocator:nil];
  if (buf == nil) {
    buf = [engine->device newBufferWithBytes:ptr length:length options:MTLResourceStorageModeShared];
  }
  engine->buffer_cache[ptr] = buf;
  return buf;
}

} // namespace

decoder_engine::~decoder_engine()
{
  engine_impl_t* engine = static_cast<engine_impl_t*>(impl);
  if (engine != nullptr) {
    engine->buffer_cache.clear();
    delete engine;
    impl = nullptr;
  }
}

bool decoder_engine::init(uint32_t n_logical, uint32_t m_logical, float factor, float beta,
                          const uint32_t* h, const layered_info& layered, bool et_enabled)
{
  engine_impl_t* engine = new engine_impl_t();
  impl                  = engine;

  engine->n_info     = n_logical - m_logical;
  engine->factor     = factor;
  engine->beta       = beta;
  engine->et_enabled = et_enabled;
  engine->layered_info = layered;
  engine->z          = layered.z;

  engine->n_aligned  = ((n_logical + 31) / 32) * 32;
  engine->m_aligned  = ((m_logical + 31) / 32) * 32;
  engine->n_h_chunks = engine->n_aligned / 32;

  engine->device = MTLCreateSystemDefaultDevice();
  if (engine->device == nil) {
    NSLog(@"ocudu Metal LDPC: no Metal device available");
    return false;
  }
  engine->queue = [engine->device newCommandQueue];

  NSError*       error   = nil;
  NSString*      src     = [NSString stringWithUTF8String:(const char*)ocudu_nms_layered_decoder_metal_source];
  id<MTLLibrary> library = [engine->device newLibraryWithSource:src options:nil error:&error];
  if (library == nil) {
    NSLog(@"ocudu Metal LDPC: shader runtime compilation failed: %@", error);
    return false;
  }

  auto make_pipeline = [&](id<MTLComputePipelineState> __strong* out, const char* name) -> bool {
    id<MTLFunction> fn = [library newFunctionWithName:[NSString stringWithUTF8String:name]];
    if (fn == nil) {
      NSLog(@"ocudu Metal LDPC: kernel '%s' not found in the shader library", name);
      return false;
    }
    *out = [engine->device newComputePipelineStateWithFunction:fn error:&error];
    if (*out == nil) {
      NSLog(@"ocudu Metal LDPC: pipeline '%s' failed: %@", name, error);
      return false;
    }
    return true;
  };
  if (!make_pipeline(&engine->p_nmsl_init, "nmsl_init") ||
      !make_pipeline(&engine->p_nmsl_convert, "nmsl_i8_to_fp16") ||
      !make_pipeline(&engine->p_nmsl_cn, "nmsl_cn_update") ||
      !make_pipeline(&engine->p_nmsl_final_syndrome, "nmsl_final_syndrome") ||
      !make_pipeline(&engine->p_nmsl_et_gate, "nmsl_et_gate")) {
    return false;
  }

  engine->buf_ctrl = [engine->device newBufferWithLength:sizeof(decode_ctrl_t)
                                                 options:MTLResourceStorageModeShared];

  // Shared (not private): the CPU recomputes the final syndrome after the kernels
  // complete (the gate clears ctrl->error_count at the end of every round).
  engine->buf_h_pred_bits = [engine->device newBufferWithLength:engine->m_aligned * sizeof(uint32_t)
                                                        options:MTLResourceStorageModeShared];

  // CSR edge layout (zero-copy) + per-edge messages + per-VN deltas.
  engine->buf_row_start = zero_copy_buffer(
      engine, engine->layered_info.row_start,
      static_cast<size_t>(engine->m_aligned + 1) * sizeof(uint32_t));
  engine->buf_edge_vn = zero_copy_buffer(
      engine, engine->layered_info.edge_vn,
      static_cast<size_t>(engine->layered_info.no_edges) * sizeof(uint32_t));
  engine->buf_c2v = [engine->device newBufferWithLength:engine->layered_info.no_edges * sizeof(uint16_t)
                                                options:MTLResourceStorageModePrivate];
  engine->buf_llr_fp16 = [engine->device newBufferWithLength:engine->n_aligned * sizeof(uint16_t)
                                                     options:MTLResourceStorageModeShared];

  // Zero-copy wrap the host-side packed H matrix (4KB-aligned, owned by the caller).
  engine->buf_h = zero_copy_buffer(engine, h, static_cast<size_t>(engine->m_aligned) *
                                                 engine->n_h_chunks * sizeof(uint32_t));

  return true;
}

int decoder_engine::decode(const void* in_fp16, uint8_t* out_bits, int max_iter, uint32_t* error_count_out)
{
  engine_impl_t* engine = static_cast<engine_impl_t*>(impl);
  if (engine == nullptr || engine->p_nmsl_init == nil) {
    return -1;
  }
  id<MTLBuffer> mtl_llr_i8 =
      zero_copy_buffer(engine, in_fp16, static_cast<size_t>(engine->n_aligned) * sizeof(int8_t));
  id<MTLCommandBuffer>        cmd_buf = [engine->queue commandBuffer];
  id<MTLComputeCommandEncoder> enc    = [cmd_buf computeCommandEncoder];

  // Stage A: reset the control block and zero the per-edge messages.
  [enc setComputePipelineState:engine->p_nmsl_init];
  [enc setBuffer:engine->buf_c2v offset:0 atIndex:0];
  [enc setBuffer:engine->buf_ctrl offset:0 atIndex:1];
  [enc dispatchThreadgroups:MTLSizeMake((engine->layered_info.no_edges + 31) / 32, 1, 1)
      threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];

  // Static bindings, bound ONCE for the whole decode: the kernels use disjoint
  // argument index ranges (CN 0-8, final syndrome 10-14, ET gate 15) and the
  // encoder's binding table is stateful across setComputePipelineState calls,
  // so only the per-layer setBytes + dispatch remain inside the loops.
  // One-time int8 -> fp16 conversion (indices 16/17), then the hot loop.
  [enc setBuffer:mtl_llr_i8 offset:0 atIndex:16];
  [enc setBuffer:engine->buf_llr_fp16 offset:0 atIndex:17];
  // CN (fused CN+VN): 0-8.
  [enc setBuffer:engine->buf_row_start offset:0 atIndex:0];
  [enc setBuffer:engine->buf_edge_vn offset:0 atIndex:1];
  [enc setBuffer:engine->buf_c2v offset:0 atIndex:2];
  [enc setBuffer:engine->buf_llr_fp16 offset:0 atIndex:3];
  [enc setBuffer:engine->buf_h_pred_bits offset:0 atIndex:4];
  [enc setBytes:&engine->factor length:sizeof(float) atIndex:6];
  [enc setBytes:&engine->beta length:sizeof(float) atIndex:7];
  [enc setBuffer:engine->buf_ctrl offset:0 atIndex:8];
  // Final syndrome: 10-14.
  [enc setBuffer:engine->buf_h offset:0 atIndex:10];
  [enc setBuffer:engine->buf_llr_fp16 offset:0 atIndex:11];
  [enc setBuffer:engine->buf_h_pred_bits offset:0 atIndex:12];
  [enc setBytes:&engine->n_h_chunks length:sizeof(uint32_t) atIndex:13];
  [enc setBuffer:engine->buf_ctrl offset:0 atIndex:14];
  // ET gate: 15.
  [enc setBuffer:engine->buf_ctrl offset:0 atIndex:15];

  // One-time int8 -> fp16 conversion (bindings 16/17 are already in place).
  [enc setComputePipelineState:engine->p_nmsl_convert];
  [enc dispatchThreads:MTLSizeMake(engine->n_aligned, 1, 1)
      threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];

  // Unrolled round loop, fully consumed by the GPU: per-layer fused CN+VN
  // dispatches (Gauss-Seidel chaining via the sequential command stream), a
  // per-round final syndrome refresh (also accumulates the unsatisfied-row
  // count), and the ET gate that stops the remaining rounds on a clean
  // syndrome. The pipeline is set once per round; per layer only the
  // layer_start setBytes and the dispatch remain.
  for (int it = 0; it < max_iter; ++it) {
    [enc setComputePipelineState:engine->p_nmsl_cn];
    for (uint32_t l = 0; l != engine->layered_info.n_layers; ++l) {
      const uint32_t layer_start = l * engine->z;
      [enc setBytes:&layer_start length:sizeof(uint32_t) atIndex:5];
      [enc dispatchThreadgroups:MTLSizeMake(engine->z, 1, 1)
          threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
    }
    [enc setComputePipelineState:engine->p_nmsl_final_syndrome];
    [enc dispatchThreadgroups:MTLSizeMake(engine->m_aligned, 1, 1)
        threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
    if (engine->et_enabled) {
      [enc setComputePipelineState:engine->p_nmsl_et_gate];
      [enc dispatchThreadgroups:MTLSizeMake(1, 1, 1) threadsPerThreadgroup:MTLSizeMake(1, 1, 1)];
    }
  }

  [enc endEncoding];
  [cmd_buf commit];
  [cmd_buf waitUntilCompleted];
  if (cmd_buf.status != MTLCommandBufferStatusCompleted) {
    NSLog(@"ocudu Metal LDPC: command buffer failed with status %lu",
          static_cast<unsigned long>(cmd_buf.status));
    return -1;
  }
  // GPU-side duration (Apple Silicon: valid for compute command buffers; 0 when unavailable).
  if (cmd_buf.GPUStartTime > 0.0 && cmd_buf.GPUEndTime > 0.0) {
    engine->last_gpu_us = (cmd_buf.GPUEndTime - cmd_buf.GPUStartTime) * 1e6;
  } else {
    engine->last_gpu_us = 0.0;
  }

  // Extract the results: hard decisions from the final fp16 LLR sign bits.
  const decode_ctrl_t* ctrl      = static_cast<const decode_ctrl_t*>(engine->buf_ctrl.contents);
  const uint16_t*      final_llr = static_cast<const uint16_t*>(engine->buf_llr_fp16.contents);
  if (out_bits != nullptr) {
    for (uint32_t i = 0; i != engine->n_info; ++i) {
      out_bits[i] = static_cast<uint8_t>((final_llr[i] >> 15) & 1U);
    }
  }
  if (error_count_out != nullptr) {
    // Recompute the final syndrome on the CPU: the gate clears ctrl->error_count
    // at the end of every round, so it does not reflect the final state.
    const uint32_t* h_pred_bits = static_cast<const uint32_t*>(engine->buf_h_pred_bits.contents);
    uint32_t        errors      = 0;
    for (uint32_t w = 0; w != engine->m_aligned; ++w) {
      errors += h_pred_bits[w] & 1u;
    }
    *error_count_out = errors;
  }
  // The gate counts only rounds whose kernels actually ran; without ET the
  // layered mode keeps reporting max_iter for backward compatibility.
  return engine->et_enabled ? static_cast<int>(ctrl->actual_iters) : max_iter;
}

uint32_t decoder_engine::get_n_info() const
{
  const engine_impl_t* engine = static_cast<const engine_impl_t*>(impl);
  return engine != nullptr ? engine->n_info : 0;
}

double decoder_engine::last_gpu_wait_us() const
{
  const engine_impl_t* engine = static_cast<const engine_impl_t*>(impl);
  return engine != nullptr ? engine->last_gpu_us : 0.0;
}

} // namespace metal
} // namespace ocudu
